-- Migration 002 — Ajout chaînes québécoises manquantes
SET search_path TO public;
ALTER TYPE store_chain ADD VALUE IF NOT EXISTS 'SUPER_C';
ALTER TYPE store_chain ADD VALUE IF NOT EXISTS 'PROVIGO';
ALTER TYPE store_chain ADD VALUE IF NOT EXISTS 'GIANT_TIGER';
ALTER TYPE store_chain ADD VALUE IF NOT EXISTS 'ADONIS';
ALTER TYPE store_chain ADD VALUE IF NOT EXISTS 'AVRIL';
ALTER TYPE store_chain ADD VALUE IF NOT EXISTS 'RACHELLE_BERY';
ALTER TYPE store_chain ADD VALUE IF NOT EXISTS 'INTERMARCHE';
ALTER TYPE store_chain ADD VALUE IF NOT EXISTS 'BONI_CHOIX';
